// src/pages/ConveyorPage.tsx
import { useState, useEffect } from 'react';
import { 
  Sparkles, Code, FileCode, TestTube, CheckCircle,
  Play, Pause, RefreshCw, Eye, Download, Terminal,
  Clock, Users, Settings, BarChart, ChevronDown,
  MessageSquare, Zap, Cpu, FileJson, Shield, Archive
} from 'lucide-react';

const ConveyorPage = () => {
  // Conveyor Belt State
  const [conveyorState, setConveyorState] = useState<'idle' | 'running' | 'paused' | 'completed'>('running');
  const [developerMode, setDeveloperMode] = useState<'review' | 'code' | 'test'>('review');

  // Conveyor Stages
  const [stages, setStages] = useState([
    {
      id: 1,
      name: 'Architecture Design',
      description: 'AI designs system architecture based on requirements',
      status: 'completed',
      icon: Sparkles,
      color: 'border-cyber-cyan',
      bgColor: 'bg-cyber-cyan/10',
      details: {
        files: ['architecture.yaml', 'tech-stack.md', 'api-contracts.json'],
        aiModel: 'GPT-4 Architect',
        duration: '3m 24s',
        tokensUsed: 2145
      }
    },
    {
      id: 2,
      name: 'Prompt Factory',
      description: 'Generates detailed prompts for each code file',
      status: 'completed',
      icon: FileCode,
      color: 'border-cyber-purple',
      bgColor: 'bg-cyber-purple/10',
      details: {
        files: ['auth-service.prompt', 'payment-api.prompt', 'user-model.prompt'],
        promptTickets: 42,
        filesGenerated: 28,
        instructionsPerFile: 12
      }
    },
    {
      id: 3,
      name: 'Code Generation',
      description: 'AI writes code based on prompt tickets',
      status: 'active',
      icon: Code,
      color: 'border-cyber-green',
      bgColor: 'bg-cyber-green/10',
      details: {
        currentFile: 'src/services/auth.service.ts',
        progress: 24,
        totalFiles: 42,
        filesCompleted: 10,
        aiModel: 'CodeLlama 34B'
      }
    },
    {
      id: 4,
      name: 'Developer Review',
      description: 'Human review and adjustment of generated code',
      status: 'pending',
      icon: Users,
      color: 'border-cyber-yellow',
      bgColor: 'bg-cyber-yellow/10',
      details: {
        filesReady: 10,
        filesReviewed: 3,
        changesRequested: 2,
        waitingFor: ['farid@vambuy.com', 'alex@vambuy.com']
      }
    },
    {
      id: 5,
      name: 'Test Synthesis',
      description: 'AI generates comprehensive test suites',
      status: 'pending',
      icon: TestTube,
      color: 'border-cyber-magenta',
      bgColor: 'bg-cyber-magenta/10',
      details: {
        testTypes: ['unit', 'integration', 'e2e'],
        coverageTarget: '90%',
        estimatedTime: '2m 15s'
      }
    },
    {
      id: 6,
      name: 'Quality Gate',
      description: 'Final validation and artifact generation',
      status: 'pending',
      icon: Shield,
      color: 'border-cyber-blue',
      bgColor: 'bg-cyber-blue/10',
      details: {
        checks: ['linting', 'security', 'performance', 'contract'],
        passing: 0,
        total: 4
      }
    }
  ]);

  // Generated Files
  const [generatedFiles, setGeneratedFiles] = useState([
    { id: 1, name: 'auth.service.ts', status: 'generated', size: '4.2KB', aiConfidence: 92, reviewed: false },
    { id: 2, name: 'payment.processor.ts', status: 'generated', size: '6.7KB', aiConfidence: 88, reviewed: true },
    { id: 3, name: 'user.model.ts', status: 'generating', size: '--', aiConfidence: 0, reviewed: false },
    { id: 4, name: 'database.config.ts', status: 'pending', size: '--', aiConfidence: 0, reviewed: false },
    { id: 5, name: 'api.routes.ts', status: 'generated', size: '3.1KB', aiConfidence: 95, reviewed: false },
    { id: 6, name: 'logger.service.ts', status: 'generated', size: '2.8KB', aiConfidence: 90, reviewed: true },
  ]);

  // Live Logs
  const [logs, setLogs] = useState([
    '[14:30] [ARCHITECT] ✅ Architecture design completed. 3 options presented.',
    '[14:32] [ARCHITECT] 📋 Generated architectural contract with 15 constraints.',
    '[14:35] [PROMPT-FACTORY] 🏭 Started generating prompts for 42 files...',
    '[14:37] [PROMPT-FACTORY] 📄 Created prompt ticket: auth.service.ts (12 instructions)',
    '[14:39] [CODE-GEN] 🤖 Processing: src/services/auth.service.ts',
    '[14:40] [CODE-GEN] ⚙️ Using guardrails: JWT authentication, bcrypt hashing',
    '[14:42] [CODE-GEN] ✅ Generated auth.service.ts (92% confidence)',
    '[14:43] [CODE-GEN] 🤖 Processing: src/services/payment.processor.ts',
  ]);

  // Project Stats
  const [projectStats] = useState({
    totalFiles: 42,
    filesGenerated: 10,
    filesReviewed: 3,
    aiConfidence: 89,
    timeSaved: '12h 30m',
    tokensUsed: 12500
  });

  const projectName = 'VamBuy Cyber';

  // Code Preview
  const [codePreview] = useState(`// src/services/auth.service.ts
// Generated by AI - Following architectural contract AUTH-001

import { Injectable } from '@nestjs/common';
import * as bcrypt from 'bcrypt';
import { JwtService } from '@nestjs/jwt';
import { UserRepository } from '../repositories/user.repository';

@Injectable()
export class AuthService {
  constructor(
    private userRepository: UserRepository,
    private jwtService: JwtService,
  ) {}

  /**
   * Register new user with email validation and password hashing
   * @guardrail: Passwords must be hashed with bcrypt (cost factor: 12)
   * @constraint: Email must be unique across system
   */
  async register(email: string, password: string) {
    // Check email uniqueness
    const existingUser = await this.userRepository.findByEmail(email);
    if (existingUser) {
      throw new Error('Email already registered');
    }

    // Hash password as per contract
    const hashedPassword = await bcrypt.hash(password, 12);
    
    // Create user with hashed password
    const user = await this.userRepository.create({
      email,
      password: hashedPassword,
      createdAt: new Date(),
    });

    // Generate JWT token
    const token = this.jwtService.sign({
      userId: user.id,
      email: user.email,
    });

    return { user, token };
  }

  // ... more methods following architectural constraints
}`);

  // Actions
  const handleStartConveyor = () => {
    setConveyorState('running');
    
    // Simulate conveyor progress
    const interval = setInterval(() => {
      setStages(prev => prev.map(stage => {
        if (stage.status === 'active') {
          return { ...stage, details: { ...stage.details, progress: Math.min(100, ((stage.details as any).progress || 0) + 5) } } as typeof stage;
        }
        return stage;
      }));
    }, 2000);

    setTimeout(() => clearInterval(interval), 10000);
  };

  const handleReviewFile = (fileId: number) => {
    setGeneratedFiles(prev => prev.map(file => 
      file.id === fileId ? { ...file, reviewed: !file.reviewed } : file
    ));
  };

  const handleRegenerateFile = (fileId: number) => {
    const file = generatedFiles.find(f => f.id === fileId);
    if (file) {
      setLogs(prev => [...prev, `[${new Date().toLocaleTimeString().slice(0,5)}] [DEV] 🔄 Requested regeneration: ${file.name}`]);
      
      // Simulate regeneration
      setTimeout(() => {
        setGeneratedFiles(prev => prev.map(f => 
          f.id === fileId ? { ...f, aiConfidence: Math.min(100, f.aiConfidence + 5) } : f
        ));
      }, 1500);
    }
  };

  const handleAddFeedback = (fileId: number) => {
    const file = generatedFiles.find(f => f.id === fileId);
    const feedback = prompt('Enter feedback for AI regeneration:');
    if (feedback && file) {
      setLogs(prev => [...prev, `[${new Date().toLocaleTimeString().slice(0,5)}] [FEEDBACK] ${file.name}: ${feedback}`]);
    }
  };

  // Auto-add logs
  useEffect(() => {
    if (conveyorState === 'running') {
      const interval = setInterval(() => {
        const actions = [
          '[SYSTEM] ✅ Conveyor belt operating normally',
          '[QUEUE] 📋 32 prompt tickets remaining',
          '[AI] 🤖 Processing next file: user.model.ts',
          '[GUARDRAILS] ⚙️ Enforcing: Type safety, error handling, logging',
        ];
        const randomAction = actions[Math.floor(Math.random() * actions.length)];
        setLogs(prev => [...prev, `${randomAction}`]);
      }, 5000);

      return () => clearInterval(interval);
    }
  }, [conveyorState]);

  return (
    <div className="min-h-screen bg-cyber-base text-cyber-text font-fira p-6">
      {/* Header */}
      <header className="flex justify-between items-center mb-8">
        <div>
          <h1 className="text-3xl font-bold font-orbitron animate-glitch" style={{ color: '#4C29BD' }}>
            DEVFLOW CONVEYOR v1.0
          </h1>
          <div className="flex items-center gap-4 mt-2">
            <div className="flex items-center gap-2 text-sm">
              <Zap size={14} className="text-cyber-yellow" />
              <span className="text-cyber-magenta">Project: <strong>{projectName}</strong></span>
            </div>
            <div className="flex items-center gap-2 text-sm">
              <Cpu size={14} className="text-cyber-cyan" />
              <span className="text-cyber-green">AI Agents: 4 active</span>
            </div>
            <div className="flex items-center gap-2 text-sm">
              <Clock size={14} className="text-cyber-blue" />
              <span>Time saved: {projectStats.timeSaved}</span>
            </div>
          </div>
        </div>
        
        <div className="flex items-center gap-3">
          <div className="text-right">
            <div className="text-sm text-cyber-cyan">Tokens used: {projectStats.tokensUsed.toLocaleString()}</div>
            <div className="text-xs text-gray-400">AI Confidence: {projectStats.aiConfidence}%</div>
          </div>
          <button className="px-4 py-2 bg-cyber-green text-cyber-base font-bold rounded hover:animate-pulseNeon transition">
            <Settings size={16} className="inline mr-2" />
            Settings
          </button>
        </div>
      </header>

      {/* Conveyor Belt Visualization */}
      <div className="mb-8">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-xl font-orbitron text-cyber-cyan">AI DEVELOPMENT CONVEYOR BELT</h2>
          <div className="flex items-center gap-2">
            <button
              onClick={handleStartConveyor}
              className={`px-4 py-2 rounded font-bold flex items-center gap-2 ${
                conveyorState === 'running' 
                  ? 'bg-cyber-green text-cyber-base' 
                  : 'bg-cyber-cyan text-cyber-base'
              }`}
            >
              {conveyorState === 'running' ? <Pause size={16} /> : <Play size={16} />}
              {conveyorState === 'running' ? 'Pause Conveyor' : 'Start Conveyor'}
            </button>
            <button className="px-4 py-2 border border-cyber-purple text-cyber-purple rounded hover:bg-cyber-purple/10">
              <RefreshCw size={16} />
            </button>
          </div>
        </div>

        {/* Conveyor Stages */}
        <div className="relative">
          {/* Conveyor Line */}
          <div className="absolute top-12 left-0 right-0 h-1 bg-gradient-to-r from-cyber-cyan via-cyber-purple to-cyber-green"></div>
          
          {/* Stages */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-6 gap-4 relative z-10">
            {stages.map((stage) => {
              const Icon = stage.icon;
              return (
                <div
                  key={stage.id}
                  className={`p-4 rounded-lg border-2 ${stage.color} ${stage.bgColor} ${
                    stage.status === 'active' ? 'animate-pulseNeon' : ''
                  }`}
                >
                  <div className="flex items-center gap-3 mb-3">
                    <div className={`p-2 rounded ${stage.bgColor}`}>
                      <Icon size={20} className={stage.color.replace('border-', 'text-')} />
                    </div>
                    <div>
                      <div className="font-orbitron text-sm">{stage.name}</div>
                      <div className="text-xs text-gray-400">Stage {stage.id}</div>
                    </div>
                  </div>
                  
                  <div className="text-xs mb-3 h-10">{stage.description}</div>
                  
                  <div className="flex justify-between items-center">
                    <span className={`text-xs px-2 py-1 rounded ${
                      stage.status === 'completed' ? 'bg-cyber-green/20 text-cyber-green' :
                      stage.status === 'active' ? 'bg-cyber-cyan/20 text-cyber-cyan animate-pulse' :
                      'bg-gray-700 text-gray-400'
                    }`}>
                      {stage.status.toUpperCase()}
                    </span>
                    <button className="text-xs text-cyber-cyan hover:text-white">
                      <ChevronDown size={14} />
                    </button>
                  </div>
                  
                  {/* Progress bar for active stage */}
                  {stage.status === 'active' && stage.details.progress && (
                    <div className="mt-3">
                      <div className="flex justify-between text-xs mb-1">
                        <span>Progress</span>
                        <span>{stage.details.progress}%</span>
                      </div>
                      <div className="h-1 bg-gray-700 rounded-full overflow-hidden">
                        <div 
                          className="h-full bg-cyber-green transition-all duration-300"
                          style={{ width: `${stage.details.progress}%` }}
                        ></div>
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Main Content Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
        {/* Left Column: Generated Files & Review */}
        <div className="lg:col-span-2">
          {/* File Management */}
          <div className="bg-gray-900/30 border border-cyber-cyan/30 rounded-lg p-5 mb-6">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-cyber-cyan font-orbitron flex items-center gap-2">
                <FileCode size={18} /> Generated Files ({projectStats.filesGenerated}/{projectStats.totalFiles})
              </h3>
              <div className="flex gap-2">
                <button 
                  onClick={() => setDeveloperMode('review')}
                  className={`px-3 py-1 text-sm rounded ${developerMode === 'review' ? 'bg-cyber-cyan text-cyber-base' : 'border border-cyber-cyan text-cyber-cyan'}`}
                >
                  Review
                </button>
                <button 
                  onClick={() => setDeveloperMode('code')}
                  className={`px-3 py-1 text-sm rounded ${developerMode === 'code' ? 'bg-cyber-purple text-cyber-base' : 'border border-cyber-purple text-cyber-purple'}`}
                >
                  Code View
                </button>
                <button 
                  onClick={() => setDeveloperMode('test')}
                  className={`px-3 py-1 text-sm rounded ${developerMode === 'test' ? 'bg-cyber-magenta text-cyber-base' : 'border border-cyber-magenta text-cyber-magenta'}`}
                >
                  Tests
                </button>
              </div>
            </div>

            {/* Files Table */}
            <div className="space-y-2 mb-4 max-h-80 overflow-y-auto">
              {generatedFiles.map((file) => (
                <div key={file.id} className="bg-gray-800/50 p-3 rounded hover:bg-gray-800/70 transition">
                  <div className="flex justify-between items-center">
                    <div className="flex items-center gap-3">
                      <div className={`w-3 h-3 rounded-full ${
                        file.status === 'generated' ? 'bg-cyber-green' :
                        file.status === 'generating' ? 'bg-cyber-yellow animate-pulse' :
                        'bg-gray-600'
                      }`}></div>
                      <div>
                        <div className="font-medium">{file.name}</div>
                        <div className="text-xs text-gray-400">
                          {file.size} • AI Confidence: {file.aiConfidence}%
                        </div>
                      </div>
                    </div>
                    
                    <div className="flex items-center gap-2">
                      {file.reviewed ? (
                        <span className="text-xs px-2 py-1 bg-cyber-green/20 text-cyber-green rounded">
                          <CheckCircle size={12} className="inline mr-1" />
                          Reviewed
                        </span>
                      ) : (
                        <span className="text-xs px-2 py-1 bg-cyber-yellow/20 text-cyber-yellow rounded">
                          Needs Review
                        </span>
                      )}
                      
                      <button
                        onClick={() => handleReviewFile(file.id)}
                        className="text-cyber-cyan hover:text-white"
                        title="Toggle Review Status"
                      >
                        <Eye size={14} />
                      </button>
                      <button
                        onClick={() => handleRegenerateFile(file.id)}
                        className="text-cyber-purple hover:text-white"
                        title="Regenerate with AI"
                      >
                        <RefreshCw size={14} />
                      </button>
                      <button
                        onClick={() => handleAddFeedback(file.id)}
                        className="text-cyber-blue hover:text-white"
                        title="Add Feedback"
                      >
                        <MessageSquare size={14} />
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {/* Code Preview */}
            {developerMode === 'code' && (
              <div className="mt-4 border-t border-gray-700 pt-4">
                <h4 className="text-sm font-medium mb-2 flex items-center gap-2">
                  <Code size={14} /> Code Preview
                </h4>
                <pre className="bg-black/50 p-4 rounded text-xs font-mono overflow-x-auto max-h-64 overflow-y-auto">
                  <code className="text-cyber-green">{codePreview}</code>
                </pre>
              </div>
            )}
          </div>

          {/* Project Stats */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="bg-gray-900/30 border border-cyber-green/30 p-4 rounded">
              <div className="text-xs text-gray-400 mb-1">Files Generated</div>
              <div className="text-2xl font-bold text-cyber-green">{projectStats.filesGenerated}</div>
              <div className="text-xs">of {projectStats.totalFiles}</div>
            </div>
            <div className="bg-gray-900/30 border border-cyber-cyan/30 p-4 rounded">
              <div className="text-xs text-gray-400 mb-1">AI Confidence</div>
              <div className="text-2xl font-bold text-cyber-cyan">{projectStats.aiConfidence}%</div>
              <div className="text-xs">Average across files</div>
            </div>
            <div className="bg-gray-900/30 border border-cyber-purple/30 p-4 rounded">
              <div className="text-xs text-gray-400 mb-1">Time Saved</div>
              <div className="text-2xl font-bold text-cyber-purple">{projectStats.timeSaved}</div>
              <div className="text-xs">vs manual coding</div>
            </div>
            <div className="bg-gray-900/30 border border-cyber-yellow/30 p-4 rounded">
              <div className="text-xs text-gray-400 mb-1">Prompt Tickets</div>
              <div className="text-2xl font-bold text-cyber-yellow">42</div>
              <div className="text-xs">in queue</div>
            </div>
          </div>
        </div>

        {/* Right Column: Live Logs & Controls */}
        <div className="space-y-6">
          {/* Live Logs */}
          <div className="bg-gray-900/30 border border-cyber-magenta/30 rounded-lg p-5">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-cyber-magenta font-orbitron flex items-center gap-2">
                <Terminal size={18} /> Conveyor Logs
              </h3>
              <button 
                onClick={() => setLogs([])}
                className="text-xs text-cyber-cyan hover:text-white"
              >
                Clear
              </button>
            </div>
            
            <div className="h-64 overflow-y-auto font-mono text-xs bg-black/30 p-3 rounded">
              {logs.map((log, index) => {
                let color = 'text-cyber-cyan';
                if (log.includes('✅')) color = 'text-cyber-green';
                if (log.includes('❌')) color = 'text-red-400';
                if (log.includes('⚠️')) color = 'text-cyber-yellow';
                
                return (
                  <div key={index} className={`mb-1 ${color}`}>
                    {log}
                  </div>
                );
              })}
            </div>
          </div>

          {/* AI Controls */}
          <div className="bg-gray-900/30 border border-cyber-blue/30 rounded-lg p-5">
            <h3 className="text-cyber-blue font-orbitron mb-4 flex items-center gap-2">
              <Cpu size={18} /> AI Agent Controls
            </h3>
            
            <div className="space-y-3">
              <div className="flex justify-between items-center">
                <span className="text-sm">Architect AI</span>
                <span className="text-xs px-2 py-1 bg-cyber-green/20 text-cyber-green rounded">Active</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-sm">Prompt Factory</span>
                <span className="text-xs px-2 py-1 bg-cyber-cyan/20 text-cyber-cyan rounded">Active</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-sm">Code Generator</span>
                <span className="text-xs px-2 py-1 bg-cyber-green/20 text-cyber-green rounded">Active</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-sm">Test Generator</span>
                <span className="text-xs px-2 py-1 bg-gray-700 text-gray-400 rounded">Standby</span>
              </div>
            </div>
            
            <div className="mt-4 pt-4 border-t border-gray-700">
              <div className="text-sm mb-2">Active Constraints</div>
              <div className="space-y-2">
                <div className="text-xs bg-gray-800/50 p-2 rounded">
                  <div className="text-cyber-green">✓ Type safety required</div>
                  <div className="text-gray-400">All variables must have explicit types</div>
                </div>
                <div className="text-xs bg-gray-800/50 p-2 rounded">
                  <div className="text-cyber-green">✓ Error handling pattern</div>
                  <div className="text-gray-400">Use centralized error handler</div>
                </div>
                <div className="text-xs bg-gray-800/50 p-2 rounded">
                  <div className="text-cyber-yellow">⚠️ Logging format</div>
                  <div className="text-gray-400">JSON structured logging</div>
                </div>
              </div>
            </div>
          </div>

          {/* Quick Actions */}
          <div className="bg-gray-900/30 border border-cyber-green/30 rounded-lg p-5">
            <h3 className="text-cyber-green font-orbitron mb-4">Quick Actions</h3>
            <div className="grid grid-cols-2 gap-2">
              <button className="p-3 bg-gray-800/50 rounded hover:bg-cyber-cyan/20 transition flex flex-col items-center">
                <Download size={20} className="mb-2 text-cyber-cyan" />
                <span className="text-xs">Export Contract</span>
              </button>
              <button className="p-3 bg-gray-800/50 rounded hover:bg-cyber-purple/20 transition flex flex-col items-center">
                <FileJson size={20} className="mb-2 text-cyber-purple" />
                <span className="text-xs">View API Spec</span>
              </button>
              <button className="p-3 bg-gray-800/50 rounded hover:bg-cyber-green/20 transition flex flex-col items-center">
                <Archive size={20} className="mb-2 text-cyber-green" />
                <span className="text-xs">Generate Tests</span>
              </button>
              <button className="p-3 bg-gray-800/50 rounded hover:bg-cyber-yellow/20 transition flex flex-col items-center">
                <BarChart size={20} className="mb-2 text-cyber-yellow" />
                <span className="text-xs">Quality Report</span>
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Footer Status */}
      <div className="border-t border-gray-700 pt-4">
        <div className="flex justify-between items-center text-sm">
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <div className="w-2 h-2 bg-cyber-green rounded-full animate-pulse"></div>
              <span>Conveyor Status: <strong className="text-cyber-green">OPERATIONAL</strong></span>
            </div>
            <div className="text-gray-400">
              Next stage: <span className="text-cyber-cyan">Developer Review</span>
            </div>
          </div>
          <div className="text-xs text-gray-400">
            Session: DEVFLOW-{Date.now().toString().slice(-8)} • Updated just now
          </div>
        </div>
      </div>
    </div>
  );
};

export default ConveyorPage;